import '../ui/solar.css';
import rawData from '../../data/dataset.json?raw';
import rawEphemeris from '../../data/ephemeris.json?raw';
import report from '../../data/ephemeris-qualification.json';
import {EphemerisProvider,bodyIds} from '../physics/provider.ts';
import {norm,add,mul} from '../physics/model.ts';
import type {DatasetDraft} from '../data/dataset.ts';
import type {EphemerisData} from '../physics/ephemeris.ts';
import type {BodyId,ScaleMode,TimeRate} from '../data/contracts.ts';
import {createSolarScene} from '../rendering/solar-scene.ts';
import {SolarGestures,keyAction} from '../input/solar-gestures.ts';
import {SolarController,type SolarAction,type InputSource} from './solar-controller.ts';
import {Lifetime} from './lifecycle.ts';

export async function bootstrapSolar():Promise<void>{
  document.title='Planetario gbprof — Sole, Terra, Luna e Marte';
  const data=JSON.parse(rawData) as DatasetDraft,ephemeris=JSON.parse(rawEphemeris) as EphemerisData;
  document.body.innerHTML=`<main class="observatory">
    <header class="masthead"><div><p class="eyebrow">GBPROF / ESPLORAZIONI SCIENTIFICHE</p><h1>Planetario <span>gbprof</span></h1></div><span class="phase-tag">IL SISTEMA SOLARE<br>QUATTRO CORPI · FASE 06</span></header>
    <p id="error" class="error" role="alert" hidden></p>
    <div class="viewbar"><h2 id="view-title">Uno sguardo al sistema solare</h2><nav class="scale-controls" aria-label="Scala della rappresentazione"><button data-scale="scientific" aria-pressed="true">Scientifica</button><button data-scale="didactic" aria-pressed="false">Didattica</button><button data-scale="exploratory" aria-pressed="false">Esplorativa</button></nav></div>
    <div class="observatory-grid"><div><section class="sky" aria-label="Osservatorio tridimensionale"><canvas id="solar-canvas" tabindex="0" aria-label="Scena 3D. Frecce: orbita; Maiusc e frecce: sposta; più e meno: zoom; C: centra; Home: panoramica; Invio: osserva; Spazio: tempo; Esc: chiudi scheda."></canvas><div class="sky-top"><strong id="view-label">VISTA DEL SISTEMA</strong><span>J2000 · ECLIPJ2000</span></div><div class="marker-layer">${['sun','earth','mars'].map(id=>`<button class="body-marker" data-marker="${id}" aria-label="Seleziona ${id==='earth'?'gruppo Terra e Luna':data.bodies[id as BodyId].name}">${id==='earth'?'Terra / Luna':data.bodies[id as BodyId].name}</button>`).join('')}</div><div class="sky-tools"><button id="zoom-plus" aria-label="Avvicina la vista">+</button><button id="zoom-minus" aria-label="Allontana la vista">−</button><button id="recenter" aria-label="Centra la vista">⌖</button></div><div class="sky-bottom"><span id="guide-legend">ELLISSI DI RIFERIMENTO · EMB E MARTE</span><span class="fps" id="fps"></span></div></section><div class="navigation-bar" role="group" aria-label="Gesto sulla scena"><button id="orbit-mode" aria-pressed="true">Orbita</button><button id="pan-mode" aria-pressed="false">Sposta</button><span>Un dito trascina · due dita spostano e ingrandiscono</span></div><p class="scale-note" id="scale-note"></p></div>
    <aside class="body-panel" aria-label="Corpi e osservazione"><nav class="body-list" aria-label="Seleziona un corpo">${bodyIds.map(id=>`<button data-body="${id}" aria-pressed="${id==='earth'}"><i style="--body-color:${({sun:'#efba66',earth:'#62accb',moon:'#b8bab7',mars:'#c78666'})[id]}"></i>${data.bodies[id].name}</button>`).join('')}</nav><button id="info-toggle" class="secondary" aria-expanded="true" aria-controls="body-info">Chiudi scheda</button><div id="body-info"><div><p class="eyebrow">OSSERVA</p><h2 id="body-name">Terra</h2><p class="kind" id="body-kind">Pianeta · sistema Terra–Luna</p></div><dl><div><dt>Raggio medio volumetrico</dt><dd id="body-radius"></dd></div><div><dt id="distance-label">Distanza dal Sole · tra i centri</dt><dd id="body-distance"></dd></div><div><dt id="speed-label">Velocità rispetto al Sole</dt><dd id="body-speed"></dd></div></dl><button class="observe" id="observe">Osserva Terra</button><button class="secondary" id="overview">Vista del sistema</button><p class="panel-note" id="panel-note">In scala reale, i pianeti sono quasi invisibili dalla panoramica. Seleziona un corpo e osservalo da vicino.</p><div class="toggles"><label><input type="checkbox" id="guides" checked> Guide orbitali</label><label><input type="checkbox" id="axes"> Assi di rotazione</label></div></div></aside></div>
    <section class="timebar" aria-label="Tempo della simulazione"><div class="time-readout"><strong id="time">J2000 + 0,000 giorni</strong><small id="clock-status">IN PAUSA · EPOCA IN TDB</small></div><button class="play" id="play">Avvia</button><button id="reset">Ripristina J2000</button><label>Velocità <select id="rate">${[1,10,100,1000,10000,100000].map(rate=>`<option value="${rate}">×${rate.toLocaleString('it-IT')}</option>`).join('')}</select></label><label class="timeline">Istante · giorni da J2000 <input id="timeline" type="range" min="-15" max="15" step="0.01" value="0" aria-label="Giorni da J2000" aria-valuetext="0 giorni da J2000"></label><small class="timeline-hint">−15 giorni ← → +15 giorni · scegli un istante per fermare il tempo</small></section>
    <p class="notice" id="status" role="status">Verifica del dataset…</p><p class="model-note">Intervallo validato: J2000-TDB ±15 giorni. Posizioni geometriche JPL; rotazioni semplificate. Le ellissi complete sono riferimenti del modello, non traiettorie storiche. Nessuna previsione di eclissi. Il campo stellare è illustrativo.</p>
    <details class="reference-note"><summary>Fonti, precisione e limiti della rappresentazione</summary><p>Posizioni: <a href="https://ssd.jpl.nasa.gov/horizons/manual.html" target="_blank" rel="noreferrer">NASA JPL Horizons</a>, DE441 e mar099; campioni orari, interpolazione cubica di posizione e velocità. Confronto su 720 campioni intermedi per ciascuno dei cinque stati. Luna–Terra: errore misurato massimo 0,016 m. Questo numero riguarda l’interpolazione dei vettori JPL, non l’accuratezza fisica assoluta delle effemeridi.</p><p>Raggi e orientamento: <a href="https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/" target="_blank" rel="noreferrer">NAIF PCK00011</a>. Polo iniziale e rotazione uniforme: nessuna orientazione ITRF, librazione lunare accurata o rotazione differenziale del Sole. Superfici sferiche di volume equivalente agli ellissoidi. La luce segue la direzione geometrica del Sole; non sono simulate ombre reciproche.</p><p>Texture: <a href="https://www.solarsystemscope.com/textures/" target="_blank" rel="noreferrer">Solar System Scope / INOVE</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>, JPEG 2K originali. Mappe elaborate a scopo illustrativo; colori e dettagli non sono osservazioni dell’istante simulato. Fotosfera del Sole illustrativa. Nessuna nuvola o atmosfera aggiuntiva.</p><p>La scala didattica ingrandisce soltanto i raggi nella vista del sistema. Terra e Luna possono sovrapporsi: si scelgono separatamente nell’elenco. I marcatori indicano la posizione, non la dimensione. Nelle viste dei corpi tutti i raggi tornano reali. Le stelle sono una distribuzione sintetica, senza identità di catalogo.</p><p>Il modello iniziale a tre ellissi è stato verificato ma escluso dal movimento: superava la soglia di errore della Luna. La revisione della Fase 5 usa il provider di effemeridi previsto nell’architettura, mantenendo intervallo e soglie. I rapporti riproducibili sono nel <a href="https://github.com/gb69prof/UTILITY/tree/main/planetario/data" target="_blank" rel="noreferrer">repository</a>.</p></details>
    <footer class="bottomline"><span>Mouse: trascina · Maiusc + trascina: sposta · rotella: zoom. Tastiera sulla scena: frecce, Maiusc + frecce, +/−, C per centrare, Home per panoramica, Invio per osservare, Spazio per avviare/fermare, Esc per chiudere la scheda.</span><span>Versione 0.6.0 <a class="technical-link" href="?technical=1">Collaudo 3D / VR</a></span></footer></main>`;
  const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
  const life=new Lifetime(),events=new AbortController();life.own(()=>events.abort());
  const provider=new EphemerisProvider(rawData,rawEphemeris,report);life.own(()=>provider.dispose());
  const ready=await provider.initialize(events.signal);if(!ready.ok)throw new Error(ready.error.message);
  const controller=new SolarController(performance.now()),{clock,view}=controller;life.own(()=>controller.dispose());let lost=false,panMode=false;
  const canvas=el<HTMLCanvasElement>('solar-canvas'),notice=(s:string)=>{el('status').textContent=s;};
  const renderer=createSolarScene(canvas,data,ephemeris,notice,value=>{lost=value;const now=performance.now();if(value)clock.pause('tracking-unavailable',now);else clock.clearBlock('tracking-unavailable',now);});life.own(()=>renderer.dispose());
  const numbers=new Intl.NumberFormat('it-IT',{maximumFractionDigits:1});
  let infoOrigin:HTMLElement=el('info-toggle');
  function sync(){const id=controller.selected;
    for(const b of document.querySelectorAll<HTMLButtonElement>('[data-body]'))b.setAttribute('aria-pressed',String(b.dataset['body']===id));
    for(const b of document.querySelectorAll<HTMLButtonElement>('[data-scale]'))b.setAttribute('aria-pressed',String(b.dataset['scale']===view.mode));
    el('body-name').textContent=data.bodies[id].name;el('body-kind').textContent=({sun:'Stella · fotosfera',earth:'Pianeta · sistema Terra–Luna',moon:'Satellite naturale della Terra',mars:'Pianeta roccioso'})[id];el('observe').textContent='Osserva '+data.bodies[id].name;
    el('body-info').hidden=!controller.infoOpen;el('info-toggle').setAttribute('aria-expanded',String(controller.infoOpen));el('info-toggle').textContent=controller.infoOpen?'Chiudi scheda':'Mostra scheda';
    el('view-title').textContent=view.focus?'Osserva '+data.bodies[view.focus].name:'Uno sguardo al sistema solare';
    canvas.dataset['selected']=id;canvas.dataset['selections']=String(controller.selections);canvas.dataset['actions']=String(controller.accepted);canvas.dataset['lastAction']=controller.lastAction;
  }
  function send(action:SolarAction,source:InputSource='ui'){
    if(action.type==='panView')action={...action,aspect:canvas.clientWidth/Math.max(1,canvas.clientHeight)};
    if(action.type==='selectBody'||action.type==='openInfo'){const active=document.activeElement;if(active instanceof HTMLElement)infoOrigin=active;}
    const restore=action.type==='closeInfo'&&el('body-info').contains(document.activeElement);
    if(controller.send(action,source,performance.now())){sync();if(restore)infoOrigin.focus({preventScroll:true});}
  }
  const on=(id:string,fn:()=>void)=>el(id).addEventListener('click',fn,{signal:events.signal});
  for(const button of document.querySelectorAll<HTMLButtonElement>('[data-body]'))button.addEventListener('click',()=>send({type:'selectBody',bodyId:button.dataset['body'] as BodyId}),{signal:events.signal});
  for(const button of document.querySelectorAll<HTMLButtonElement>('[data-scale]'))button.addEventListener('click',()=>send({type:'setScaleMode',mode:button.dataset['scale'] as ScaleMode}),{signal:events.signal});
  for(const button of document.querySelectorAll<HTMLButtonElement>('[data-marker]'))button.addEventListener('click',e=>{if(e.detail!==0)return;send({type:'selectBody',bodyId:button.dataset['marker'] as BodyId});if(controller.selected==='earth')notice('Gruppo Terra–Luna: scegli Terra o Luna nell’elenco.');},{signal:events.signal});
  on('observe',()=>send({type:'focusBody',bodyId:controller.selected}));on('overview',()=>send({type:'overview'}));on('recenter',()=>send({type:'recenterView'}));
  on('info-toggle',()=>send({type:controller.infoOpen?'closeInfo':'openInfo'}));
  on('zoom-plus',()=>send({type:'zoomView',logDistanceDelta:-.2}));on('zoom-minus',()=>send({type:'zoomView',logDistanceDelta:.2}));
  on('play',()=>send({type:clock.sample(performance.now()).status==='running'?'pauseTime':'resumeTime'}));
  on('reset',()=>{send({type:'resetTime'});el<HTMLSelectElement>('rate').value='1';});
  el<HTMLSelectElement>('rate').addEventListener('change',event=>send({type:'setTimeRate',rate:Number((event.target as HTMLSelectElement).value) as TimeRate}),{signal:events.signal});
  el<HTMLInputElement>('timeline').addEventListener('input',event=>send({type:'seekTime',tTdbSeconds:Number((event.target as HTMLInputElement).value)*86400}),{signal:events.signal});
  for(const key of ['guides','axes'] as const)el<HTMLInputElement>(key).addEventListener('change',()=>send({type:'setGuide',key,value:el<HTMLInputElement>(key).checked}),{signal:events.signal});
  const gestures=new SolarGestures();
  const cancel=()=>{gestures.cancel();markerTargets.clear();for(const id of captured){if(canvas.hasPointerCapture(id))canvas.releasePointerCapture(id);}captured.clear();};
  const captured=new Set<number>(),markerTargets=new Map<number,BodyId>();
  for(const mode of ['orbit','pan'])on(mode+'-mode',()=>{cancel();panMode=mode==='pan';el('orbit-mode').setAttribute('aria-pressed',String(!panMode));el('pan-mode').setAttribute('aria-pressed',String(panMode));});
  function down(e:PointerEvent,marker?:BodyId){if(e.button!==0&&e.button!==2)return;e.preventDefault();canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);captured.add(e.pointerId);if(marker)markerTargets.set(e.pointerId,marker);gestures.down(e.pointerId,e.clientX,e.clientY,panMode||e.shiftKey||e.button===2);}
  canvas.addEventListener('pointerdown',e=>down(e),{signal:events.signal});
  for(const marker of document.querySelectorAll<HTMLButtonElement>('[data-marker]'))marker.addEventListener('pointerdown',e=>down(e,marker.dataset['marker'] as BodyId),{signal:events.signal});
  canvas.addEventListener('pointermove',e=>{for(const a of gestures.move(e.pointerId,e.clientX,e.clientY,canvas.clientWidth,canvas.clientHeight))send(a,e.pointerType==='touch'?'touch':'mouse');},{signal:events.signal});
  canvas.addEventListener('pointerup',e=>{if(gestures.up(e.pointerId,e.clientX,e.clientY)){const hit=markerTargets.get(e.pointerId)??renderer.pick(e.clientX,e.clientY);if(hit)send({type:'selectBody',bodyId:hit},e.pointerType==='touch'?'touch':'mouse');}markerTargets.delete(e.pointerId);captured.delete(e.pointerId);if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);},{signal:events.signal});
  canvas.addEventListener('lostpointercapture',e=>{if(captured.has(e.pointerId))cancel();},{signal:events.signal});
  canvas.addEventListener('pointercancel',cancel,{signal:events.signal});canvas.addEventListener('blur',cancel,{signal:events.signal});window.addEventListener('blur',cancel,{signal:events.signal});
  canvas.addEventListener('contextmenu',e=>e.preventDefault(),{signal:events.signal});
  const resize=new ResizeObserver(cancel);resize.observe(canvas);life.own(()=>{resize.disconnect();cancel();});
  canvas.addEventListener('wheel',e=>{e.preventDefault();send({type:'zoomView',logDistanceDelta:e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?canvas.clientHeight:1)*.0015},'mouse');},{signal:events.signal,passive:false});
  canvas.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const action=keyAction(e.key,e.shiftKey,controller.selected,clock.sample(performance.now()).status==='running');if(action){e.preventDefault();if(e.repeat&&['focusBody','overview','resumeTime','pauseTime','closeInfo'].includes(action.type))return;send(action,'keyboard');}},{signal:events.signal});
  document.querySelector('.body-panel')!.addEventListener('keydown',event=>{const e=event as KeyboardEvent;if(e.key==='Escape'){e.preventDefault();send({type:'closeInfo'},'keyboard');}},{signal:events.signal});
  document.addEventListener('visibilitychange',()=>{const now=performance.now();cancel();if(document.hidden)clock.pause('hidden',now);else clock.clearBlock('hidden',now);},{signal:events.signal});
  let frames=0,lastUi=0;
  function render(){if(life.disposed||lost)return;try{const now=performance.now(),time=clock.sample(now),snapshot=provider.getSnapshot(time.tTdbSeconds);if(!snapshot.ok)throw new Error(snapshot.error.message);controller.snapshot=snapshot.value;
    el('scale-note').textContent=renderer.apply(snapshot.value,view);renderer.draw();frames++;
    for(const button of document.querySelectorAll<HTMLButtonElement>('[data-marker]')){const id=button.dataset['marker'] as BodyId,p=renderer.marker(id);button.hidden=view.context!=='system'||!p.visible||p.x<50||p.x>canvas.clientWidth-50||p.y<60||p.y>canvas.clientHeight-45;button.style.left=p.x+'px';button.style.top=p.y+'px';}
    el('view-label').textContent=view.context==='system'?'VISTA DEL SISTEMA':`VISTA ${view.context==='local'?'LOCALE':'RAVVICINATA'} · ${data.bodies[view.focus!].name.toUpperCase()}`;
    el('guide-legend').textContent=!view.guides?'GUIDE NASCOSTE':view.context==='system'?'ELLISSI DI RIFERIMENTO · EMB E MARTE':view.focus==='earth'||view.focus==='moon'?'PERCORSO LUNARE RELATIVO · 30 GIORNI':'SUPERFICIE · MAPPA ILLUSTRATIVA';
    if(now-lastUi>150){const s=snapshot.value.states[controller.selected],r=data.bodies[controller.selected].physical.meanRadius!.value;el('body-radius').textContent=numbers.format(r/1000)+' km';
      const relative=controller.selected==='moon'?add(s.positionM,mul(snapshot.value.states.earth.positionM,-1)):s.positionM,velocity=controller.selected==='moon'?add(s.velocityMps,mul(snapshot.value.states.earth.velocityMps,-1)):s.velocityMps;
      el('distance-label').textContent=controller.selected==='moon'?'Distanza dalla Terra · tra i centri':'Distanza dal Sole · tra i centri';el('body-distance').textContent=controller.selected==='sun'?'Origine del sistema':numbers.format(norm(relative)/1000)+' km';el('speed-label').textContent=controller.selected==='moon'?'Velocità rispetto alla Terra':'Velocità rispetto al Sole';el('body-speed').textContent=controller.selected==='sun'?'Origine eliocentrica':numbers.format(norm(velocity)/1000)+' km/s';
      el('time').textContent='J2000 '+(time.tTdbSeconds<0?'−':'+')+' '+Math.abs(time.tTdbSeconds/86400).toLocaleString('it-IT',{minimumFractionDigits:3,maximumFractionDigits:3})+' giorni';el('clock-status').textContent=(time.reasons.includes('range-end')?'LIMITE +15 GIORNI · SCEGLI UN ISTANTE PRECEDENTE':time.status==='running'?'IN MOVIMENTO · TEMPO TDB':'IN PAUSA · TEMPO TDB');el('play').textContent=time.status==='running'?'Pausa':'Avvia';el<HTMLButtonElement>('play').disabled=time.reasons.includes('range-end');canvas.dataset['clock']=time.status;const timeline=el<HTMLInputElement>('timeline');if(document.activeElement!==timeline)timeline.value=String(time.tTdbSeconds/86400);timeline.setAttribute('aria-valuetext',(time.tTdbSeconds/86400).toLocaleString('it-IT',{maximumFractionDigits:3})+' giorni da J2000');
      el('fps').textContent=Math.round(frames*1000/(now-lastUi))+' FPS';frames=0;lastUi=now;
    }
  }catch(e){clock.pause('user',performance.now());renderer.engine.stopRenderLoop(render);el('error').hidden=false;el('error').textContent=String(e);}}
  renderer.engine.runRenderLoop(render);life.own(()=>renderer.engine.stopRenderLoop(render));
  notice('Scegli un corpo, poi premi Osserva. Il tempo parte solo con Avvia.');sync();
  window.addEventListener('pagehide',event=>{if(event.persisted)clock.pause('hidden',performance.now());else life.dispose();},{signal:events.signal});
  window.addEventListener('pageshow',event=>{if(event.persisted)clock.clearBlock('hidden',performance.now());},{signal:events.signal});
  if(import.meta.hot)import.meta.hot.dispose(()=>life.dispose());
}
