import {ERA_BOUNDARY,CURRENT_YEAR,coordinate,periodLabel,durationLabel,momentLabel,ticks,amount} from './chronology.mjs';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const MIN_SPAN=6,MAX_SPAN=3_000_000,MAX_TIME=coordinate(null),MIN_TIME=coordinate({bp:2400000});
const state={center:ERA_BOUNDARY,span:4000,mode:'subjects',region:'all',selected:null};
const chart=$('timeline'),rows=$('rows'),scroller=$('rows-scroll');
let subjects=[],epochs=[],all=[],width=900,pending=false,renderKey='',nodeMap=new Map(),inertia=0,toastTimer=0,returnFocus=null;
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const zoomValue=span=>100*(1-Math.log(span/MIN_SPAN)/Math.log(MAX_SPAN/MIN_SPAN));
const spanValue=value=>MIN_SPAN*(MAX_SPAN/MIN_SPAN)**(1-value/100);
function announce(message,visible=false){$('status').textContent=message;if(visible){$('status').classList.remove('sr-only');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('status').classList.add('sr-only'),4500);}}
function schedule(){if(!pending){pending=true;requestAnimationFrame(()=>{pending=false;render();});}}
function stop(){cancelAnimationFrame(inertia);inertia=0;}
function pan(delta){state.center=clamp(state.center+delta,MIN_TIME,MAX_TIME);schedule();}
function zoom(factor,anchor=.5){stop();const before=state.span;state.span=clamp(state.span*factor,MIN_SPAN,MAX_SPAN);state.center=clamp(state.center+(anchor-.5)*(before-state.span),MIN_TIME,MAX_TIME);schedule();}
function setMode(mode){state.mode=mode;document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',b.dataset.mode===mode);});$('region').disabled=mode==='epochs';renderKey='';schedule();}
function home(){stop();state.center=ERA_BOUNDARY;state.span=4000;state.region='all';$('region').value='all';setMode('subjects');closeDetail();scroller.scrollTop=0;schedule();announce('Passaggio tra 1 a.C. e 1 d.C.');}
function focusItem(item){stop();state.center=clamp((item.a+item.b)/2,MIN_TIME,MAX_TIME);state.span=clamp((item.b-item.a)*1.35,MIN_SPAN,MAX_SPAN);state.region='all';$('region').value='all';setMode(item.type==='epoca'?'epochs':'subjects');scroller.scrollTop=0;schedule();requestAnimationFrame(()=>{const node=nodeMap.get(item.id);if(node)scroller.scrollTop=Math.max(0,node.parentElement.offsetTop-35);});}
function prepare(items){return items.map(item=>({...item,a:coordinate(item.start),b:coordinate(item.end)}));}
function assignLanes(items){
 const ends=[];
 for(const item of items){let lane=ends.findIndex(intervals=>intervals.every(i=>item.b<=i.a||item.a>=i.b));if(lane<0){lane=ends.length;ends.push([]);}ends[lane].push(item);item.lane=lane;}
}
function activeItems(){return (state.mode==='epochs'?epochs:subjects).filter(i=>{
 if(state.mode!=='epochs'&&state.region!=='all'&&i.region!==state.region)return false;
 if(i.b<state.center-state.span/2||i.a>state.center+state.span/2)return false;
 if(state.mode!=='epochs'&&i.id!==state.selected){if(state.span<100000&&i.type==='specie / gruppi umani')return false;if(state.span>200000&&i.type!=='specie / gruppi umani'&&i.b-i.a<state.span/600)return false;}
 return true;
 });}
function rebuild(visible){
 const active=document.activeElement?.dataset.id;
 const groups=new Map();for(const item of visible){const lane=state.mode==='epochs'?epochs.indexOf(item):item.lane;if(!groups.has(lane))groups.set(lane,[]);groups.get(lane).push(item);}
 rows.replaceChildren();nodeMap=new Map();
 for(const [lane,items] of [...groups].sort((a,b)=>a[0]-b[0])){
  const row=document.createElement('div');row.className='row';row.dataset.lane=lane;rows.append(row);
  for(const item of items){const node=document.createElement('button');node.type='button';node.className='bar';node.dataset.id=item.id;node.dataset.name=item.name;node.style.setProperty('--bar',item.color);node.setAttribute('aria-label',`${item.name}. ${periodLabel(item)}. Apri scheda`);node.title=`${item.name} · ${periodLabel(item)}`;node.innerHTML=`<span class="bar-content"><img src="assets/${esc(item.symbol)}.svg" alt="" draggable="false"><span class="bar-text">${esc(item.name)}<small>${esc(item.region)}</small></span></span>`;row.append(node);nodeMap.set(item.id,node);}
 }
 if(active&&nodeMap.has(active))nodeMap.get(active).focus({preventScroll:true});
}
function render(){
 width=chart.clientWidth;const left=state.center-state.span/2,visible=activeItems(),key=state.mode+visible.map(i=>i.id).join(',');
 if(key!==renderKey){renderKey=key;rebuild(visible);}
 for(const item of visible){const node=nodeMap.get(item.id),x=(item.a-left)/state.span*width,right=(item.b-left)/state.span*width,l=clamp(x,0,width),r=clamp(right,0,width),size=r-l;
  node.style.left=l+'px';node.style.width=Math.max(.5,size)+'px';node.style.setProperty('--exact-width',Math.max(.5,size)+'px');node.classList.toggle('tiny',size<16);node.classList.toggle('short',size<135);node.classList.toggle('approx',item.approx);node.classList.toggle('selected',item.id===state.selected);node.classList.toggle('clipped-start',x<0);node.classList.toggle('clipped-end',right>width);node.setAttribute('aria-pressed',item.id===state.selected);
 }
 const marks=ticks(state.center,state.span,width),boundaryX=(ERA_BOUNDARY-left)/state.span*width;
 $('ruler').innerHTML=marks.filter(t=>!(state.span>20&&Math.abs(t.value-ERA_BOUNDARY)/state.span*width<90)).map(t=>`<span class="tick" style="left:${(t.value-left)/state.span*width}px">${esc(t.label)}</span>`).join('')+(boundaryX>=0&&boundaryX<=width&&state.span>20&&state.span<30000?`<span class="boundary-label" style="left:${boundaryX}px">1 a.C. │ 1 d.C.</span>`:'');
 rows.style.backgroundImage=marks.length?marks.map(()=>`linear-gradient(90deg,#66859925 1px,transparent 1px)`).join(','):'none';rows.style.backgroundSize=marks.map(()=>'100% 100%').join(',');rows.style.backgroundPosition=marks.map(t=>`${(t.value-left)/state.span*width}px 0`).join(',');rows.style.backgroundRepeat='no-repeat';
 $('moment').textContent=momentLabel(state.center,state.span);$('moment-note').textContent=Math.abs(state.center-ERA_BOUNDARY)<.02?'Il passaggio tra le due ere':state.center===MAX_TIME?'Il presente · '+CURRENT_YEAR:state.center<coordinate({year:10000,era:'BCE'})?'BP = prima del 1950 · date approssimative':'Il momento osservato';
 $('scale-label').textContent=`${amount(Math.round(state.span))} anni sullo schermo`;$('zoom').value=zoomValue(state.span);$('zoom-in').disabled=state.span<=MIN_SPAN;$('zoom-out').disabled=state.span>=MAX_SPAN;$('past').disabled=state.center<=MIN_TIME;$('future').disabled=state.center>=MAX_TIME;
 $('visible-count').textContent=`${visible.length} ${state.mode==='epochs'?'epoche':'storie'} in vista${state.mode==='subjects'?' · '+subjects.length+' nel percorso':''}`;$('empty').hidden=visible.length>0;
 document.querySelectorAll('[data-epoch]').forEach(b=>{const item=epochs.find(i=>i.id===b.dataset.epoch);b.classList.toggle('current',state.center>=item.a&&state.center<=item.b);});
}
function selectItem(item,opener){state.selected=item.id;returnFocus=opener||chart;const panel=$('detail');panel.hidden=false;document.body.classList.add('has-detail');panel.innerHTML=`<header class="detail-head"><h1 id="detail-title">${esc(item.name)}</h1><p>${esc(item.subtitle)}</p><button class="detail-close" aria-label="Chiudi scheda">×</button></header><div class="detail-hero"><img src="${esc(item.images[0].src)}" alt="${esc(item.images[0].caption)}"><span class="hero-label">Illustrazione simbolica · ${esc(item.region)}</span></div><div class="detail-body"><div class="detail-meta"><div><strong>Periodo</strong>${esc(periodLabel(item))}</div><div><strong>Durata</strong>${esc(durationLabel(item))}</div></div><p class="tagline">${esc(item.type)} · ${esc(item.region)}</p><p class="note">${esc(item.note)}</p><h2>Storia generale</h2><p>${esc(item.history)}</p><h2>Cultura</h2><p>${esc(item.culture)}</p><h2>Immagini simbolo</h2><div class="gallery">${item.images.map(image=>`<figure><img src="${esc(image.src)}" alt="${esc(image.caption)}" loading="lazy"><figcaption>${esc(image.caption)}</figcaption></figure>`).join('')}</div><h2>Cosa ci hanno lasciato</h2><ul>${item.legacy.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><h2>Fonti per approfondire</h2><ul class="sources">${item.sources.map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a></li>`).join('')}</ul><button class="locate">Inquadra tutta la durata</button><p class="signature">GB — Linea del Tempo · gbprof</p></div>`;
 panel.scrollTop=0;panel.querySelector('.detail-close').addEventListener('click',closeDetail);panel.querySelector('.locate').addEventListener('click',()=>focusItem(item));panel.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{if(!img.src.endsWith('globe.svg'))img.src='assets/globe.svg';},{once:true}));panel.querySelector('.detail-close').focus({preventScroll:true});schedule();announce(`Scheda aperta: ${item.name}. ${periodLabel(item)}`);
}
function closeDetail(){if($('detail').hidden)return;$('detail').hidden=true;document.body.classList.remove('has-detail');state.selected=null;schedule();if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});else chart.focus({preventScroll:true});}
function results(showAll=false){const query=$('search').value.trim().toLocaleLowerCase('it');const matches=all.filter(i=>showAll||!query||`${i.name} ${i.subtitle} ${i.region} ${i.type}`.toLocaleLowerCase('it').includes(query));$('results').innerHTML=matches.length?matches.map(i=>`<button data-result="${esc(i.id)}">${esc(i.name)}<small>${esc(periodLabel(i))} · ${esc(i.region)}</small></button>`).join(''):'<p>Nessun risultato. Prova una civiltà o un’area geografica.</p>';$('results').hidden=false;$('search').setAttribute('aria-expanded','true');}
function hideResults(){$('results').hidden=true;$('search').setAttribute('aria-expanded','false');}
$('search').addEventListener('input',()=>results());$('search').addEventListener('focus',()=>{if($('search').value)results();});$('search').addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();if($('results').hidden)results();$('results').querySelector('button')?.focus();}if(e.key==='Enter'){e.preventDefault();$('results').querySelector('button')?.click();}if(e.key==='Escape')hideResults();});
$('results').addEventListener('click',e=>{const button=e.target.closest('[data-result]');if(!button)return;const item=all.find(i=>i.id===button.dataset.result);hideResults();$('search').value='';focusItem(item);selectItem(item,chart);});
$('results').addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const buttons=[...$('results').querySelectorAll('button')],index=buttons.indexOf(document.activeElement);buttons[clamp(index+(e.key==='ArrowDown'?1:-1),0,buttons.length-1)]?.focus();}});
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.search-wrap')&&!e.target.closest('#explore'))hideResults();});
$('explore').addEventListener('click',()=>{$('search').focus();results(true);});
$('home').addEventListener('click',home);$('zoom-in').addEventListener('click',()=>zoom(1/1.8));$('zoom-out').addEventListener('click',()=>zoom(1.8));$('zoom').addEventListener('input',e=>{stop();state.span=spanValue(Number(e.target.value));schedule();});
$('past').addEventListener('click',()=>{stop();pan(-state.span*.25);});$('future').addEventListener('click',()=>{stop();pan(state.span*.25);});$('today').addEventListener('click',()=>{stop();state.center=MAX_TIME;state.span=180;state.region='all';$('region').value='all';setMode('subjects');scroller.scrollTop=0;announce(`Presente: ${CURRENT_YEAR}`);});
$('region').addEventListener('change',e=>{state.region=e.target.value;renderKey='';scroller.scrollTop=0;schedule();});
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{scroller.scrollTop=0;setMode(b.dataset.mode);}));
function openInfo(){$('help').showModal();hideResults();}$('info').addEventListener('click',openInfo);$('conventions').addEventListener('click',openInfo);$('help').querySelector('.dialog-close').addEventListener('click',()=>$('help').close());
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('help').open){hideResults();closeDetail();}});
$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else announce('Su iPad usa Condividi → Aggiungi alla schermata Home.',true);}catch{announce('Schermo intero non disponibile: usa l’installazione dalla schermata Home.',true);}});
chart.addEventListener('keydown',e=>{if(e.target!==chart&&!e.target.closest('.bar'))return;if(['ArrowLeft','ArrowRight','+','=','-','Home'].includes(e.key)){e.preventDefault();stop();if(e.key==='ArrowLeft')pan(-state.span/10);else if(e.key==='ArrowRight')pan(state.span/10);else if(e.key==='Home')home();else zoom(e.key==='-'?1.8:1/1.8);}if(e.key==='ArrowDown'&&e.target===chart){e.preventDefault();scroller.scrollTop+=70;}if(e.key==='ArrowUp'&&e.target===chart){e.preventDefault();scroller.scrollTop-=70;}});
// Pointer gestures: axis lock distinguishes vertical row browsing from time travel.
const pointers=new Map();let gesture=null,suppressClickUntil=0;
chart.addEventListener('pointerdown',e=>{if(e.button!==0)return;stop();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});chart.setPointerCapture(e.pointerId);if(pointers.size===1)gesture={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,time:performance.now(),velocity:0,axis:null,moved:false,touch:e.pointerType==='touch',target:e.target.closest('[data-id]')};else if(pointers.size===2){const [a,b]=[...pointers.values()];gesture={...gesture,pinch:true,distance:Math.hypot(a.x-b.x,a.y-b.y),span:state.span,center:state.center,mid:(a.x+b.x)/2,moved:true};}});
chart.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2){const [a,b]=[...pointers.values()],distance=Math.hypot(a.x-b.x,a.y-b.y),mid=(a.x+b.x)/2,anchor=(gesture.mid-chart.getBoundingClientRect().left)/width;state.span=clamp(gesture.span*gesture.distance/Math.max(10,distance),MIN_SPAN,MAX_SPAN);state.center=clamp(gesture.center+(anchor-.5)*(gesture.span-state.span)-(mid-gesture.mid)/width*state.span,MIN_TIME,MAX_TIME);schedule();return;}if(gesture.pinch)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(!gesture.axis&&Math.hypot(dx,dy)>6){gesture.axis=Math.abs(dx)>Math.abs(dy)?'x':'y';gesture.moved=true;chart.classList.add('dragging');}const now=performance.now(),elapsed=Math.max(1,now-gesture.time);if(gesture.axis==='x'){const delta=e.clientX-gesture.lastX;pan(-delta/width*state.span);gesture.velocity=.65*gesture.velocity+.35*delta/elapsed;}else if(gesture.axis==='y'){scroller.scrollTop-=e.clientY-gesture.lastY;}gesture.lastX=e.clientX;gesture.lastY=e.clientY;gesture.time=now;});
function endPointer(e,cancelled=false){if(!pointers.has(e.pointerId))return;pointers.delete(e.pointerId);if(pointers.size)return;chart.classList.remove('dragging');const g=gesture;gesture=null;if(!g)return;
 if(g.moved||cancelled){suppressClickUntil=performance.now()+350;if(!cancelled&&g.touch&&g.axis==='x'&&!g.pinch&&!reduced.matches&&performance.now()-g.time<100){let v=g.velocity,last=performance.now();const coast=now=>{const dt=Math.min(32,now-last);last=now;v*=Math.exp(-dt/110);pan(-v*dt/width*state.span);if(Math.abs(v)>.025)inertia=requestAnimationFrame(coast);};inertia=requestAnimationFrame(coast);}return;}
 // Pointer capture retargets click to the region: explicitly activate a stationary tap.
 if(g.target&&g.target.isConnected){suppressClickUntil=performance.now()+350;const item=all.find(i=>i.id===g.target.dataset.id);if(item)selectItem(item,g.target);}
}
chart.addEventListener('pointerup',e=>endPointer(e));chart.addEventListener('pointercancel',e=>endPointer(e,true));chart.addEventListener('lostpointercapture',e=>{if(pointers.has(e.pointerId))endPointer(e,true);});
rows.addEventListener('click',e=>{if(performance.now()<suppressClickUntil){e.preventDefault();return;}const node=e.target.closest('[data-id]');if(node)selectItem(all.find(i=>i.id===node.dataset.id),node);});
chart.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();zoom(Math.exp(e.deltaY*.008),(e.clientX-chart.getBoundingClientRect().left)/width);return;}stop();if(Math.abs(e.deltaX)>Math.abs(e.deltaY)||e.shiftKey){e.preventDefault();pan((e.deltaX||e.deltaY)/width*state.span);}else if(e.target.closest('#ruler')){e.preventDefault();pan(e.deltaY/width*state.span);} // Vertical wheel over rows remains native row scrolling.
},{passive:false});
new ResizeObserver(()=>schedule()).observe(chart);
async function offline(){if(!('serviceWorker'in navigator)){$('offline-state').textContent='Questo browser non supporta la consultazione offline.';return;}try{const registration=await navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'});await navigator.serviceWorker.ready;$('offline-state').textContent='Pronto offline: struttura, testi e immagini locali sono stati memorizzati.';if(registration.waiting)announce('È disponibile un aggiornamento. Riapri l’app per caricarlo.',true);registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)announce('Aggiornamento pronto. Chiudi le finestre dell’app e riaprila.',true);});});}catch{$('offline-state').textContent='Cache offline non disponibile in questa sessione. La consultazione online resta attiva.';}}
try{
 const responses=await Promise.all([fetch('./data/civilizations.json'),fetch('./data/epochs.json')]);if(responses.some(r=>!r.ok))throw new Error('Dati non disponibili');const [data,epochData]=await Promise.all(responses.map(r=>r.json()));subjects=prepare(data.items);epochs=prepare(epochData);all=[...subjects,...epochs];
 const priority=['egizi','persiani','greci','impero-romano','kush','han','fenici','cartagine','etruschi'];subjects.sort((a,b)=>{const x=priority.indexOf(a.id),y=priority.indexOf(b.id);return (x<0?100:x)-(y<0?100:y);});assignLanes(subjects);
 $('epochs').innerHTML=epochs.map(i=>`<button data-epoch="${esc(i.id)}" aria-label="Esplora ${esc(i.name)}"><strong>${esc(i.name)}</strong><small>${esc(i.subtitle)}</small></button>`).join('');$('epochs').addEventListener('click',e=>{const b=e.target.closest('[data-epoch]');if(!b)return;const item=epochs.find(i=>i.id===b.dataset.epoch);focusItem(item);setMode('subjects');closeDetail();});
 [...new Set(subjects.map(i=>i.region))].sort((a,b)=>a.localeCompare(b,'it')).forEach(region=>{const o=document.createElement('option');o.value=region;o.textContent=region;$('region').append(o);});
 $('credits').innerHTML='<p>Panorama: illustrazione originale generata con IA per questo progetto (settembre 2026). Simboli delle schede: disegni vettoriali originali del progetto. Sono immagini evocative, non reperti o ricostruzioni scientifiche.</p>';
 render();offline();
}catch(error){$('empty').hidden=false;$('empty').textContent='Non riesco a caricare i contenuti. Ricarica la pagina quando hai una connessione.';$('visible-count').textContent='Caricamento non riuscito';console.error(error);}
