"""Deterministic cache inventory; canonical research files stay out of core cache."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
files=['./','index.html','manifest.webmanifest','css/atlas.css','js/app.js','js/model.js','assets/stockdale-1812.jpg']
files += [p.relative_to(ROOT).as_posix() for p in (ROOT/'icons').glob('*') if p.is_file()]
files += [p.relative_to(ROOT).as_posix() for p in (ROOT/'vendor').glob('*') if p.suffix in ('.mjs','.css')]
files += [p.relative_to(ROOT).as_posix() for p in (ROOT/'data').glob('MAP_*/atlas.json')]
files += ['data/MAP_10/'+n+'.json' for n in ['entities','persons','relations','issues']]
files += ['data/common/'+n for n in ['snapshots.json','sources.json','polities.json','events.json','campaigns.json','issues.json','land.geojson','campaign-routes.geojson','geometries.geojson']]
files += [p.name for p in ROOT.glob('*.md')]
checksum=hashlib.sha256(b''.join((ROOT/p).read_bytes() for p in sorted(set(files)) if p!='./')).hexdigest()[:12]
template='''/* Generated by tools/build_pwa.py. Core cache is scoped to this atlas only. */
const VERSION = 'gb-atlante-__VERSION__';
const CORE = __FILES__;
const PREFIX = 'gb-atlante-';
self.addEventListener('install', event => {
 event.waitUntil(caches.open(VERSION).then(cache => cache.addAll(CORE)));
});
self.addEventListener('activate', event => {
 event.waitUntil((async () => {
  for (const key of await caches.keys()) if (key.startsWith(PREFIX) && key !== VERSION) await caches.delete(key);
  await self.clients.claim();
 })());
});
self.addEventListener('message', event => {
 if (event.data?.type === 'ACTIVATE_UPDATE') self.skipWaiting();
});
self.addEventListener('fetch', event => {
 const url = new URL(event.request.url);
 if (event.request.method !== 'GET' || url.origin !== self.location.origin || !url.href.startsWith(self.registration.scope)) return;
 event.respondWith((async () => {
  const cache = await caches.open(VERSION);
  const cached = await cache.match(event.request, {ignoreSearch: true});
  if (cached) return cached;
  try { return await fetch(event.request); }
  catch (error) {
   if (event.request.mode === 'navigate') return await cache.match('./');
   return new Response('Risorsa non inclusa nella copia offline.', {status: 503, headers: {'Content-Type':'text/plain; charset=utf-8'}});
  }
 })());
});
'''
(ROOT/'service-worker.js').write_text(template.replace('__VERSION__',checksum).replace('__FILES__',json.dumps(sorted(set(files)))),encoding='utf-8')
(ROOT/'data/common/cache-inventory.json').write_text(json.dumps({'version':checksum,'files':sorted(set(files)),'total_bytes':sum((ROOT/p).stat().st_size for p in set(files) if p!='./')},indent=2),encoding='utf-8')
print('Offline assets',len(set(files)),'version',checksum)
