import {readFile,writeFile,readdir,stat} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
async function walk(dir){const entries=await readdir(path.join(root,dir),{withFileTypes:true});const out=[];for(const e of entries){const p=path.posix.join(dir,e.name);if(e.isDirectory())out.push(...await walk(p));else out.push(p);}return out;}
const authors=JSON.parse(await readFile(path.join(root,'data/authors.json'),'utf8'));
const core=['./','index.html','styles.css','app.js','core.js','manifest.json','assets/hero.webp','assets/icon.svg','assets/icon-192.png','assets/icon-512.png','assets/icon-maskable.png','data/authors.json','data/movements.json','data/pwa-links.json','data/existing-pwa-map.json','docs/FONTI-E-METODO.md',...authors.map(a=>a.immagine).filter(Boolean)];
const hash=createHash('sha256');let bytes=0;
for(const f of core.filter(f=>f!=='./')){const data=await readFile(path.join(root,f));hash.update(data);bytes+=data.length;}
const version=hash.digest('hex').slice(0,14);
const sw=`// Generated by npm run build. Cache namespace is restricted to this PWA.\nconst PREFIX='gb-letteratura-';\nconst CACHE=PREFIX+'${version}';\nconst CORE=${JSON.stringify(core)};\nself.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)));});\nself.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith(PREFIX)&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()));});\nself.addEventListener('fetch',event=>{const url=new URL(event.request.url);if(event.request.method!=='GET'||url.origin!==self.location.origin||!url.href.startsWith(self.registration.scope))return;event.respondWith(caches.open(CACHE).then(async cache=>{const cached=await cache.match(event.request,{ignoreSearch:true});if(cached)return cached;try{const response=await fetch(event.request);return response;}catch(error){if(event.request.mode==='navigate')return (await cache.match('./'))||(await cache.match('index.html'));throw error;}}));});\n`;
await writeFile(path.join(root,'service-worker.js'),sw);
console.log(JSON.stringify({version,coreFiles:core.length,offlineBytes:bytes,authors:authors.length}));
