/* Generated by tools/build_pwa.py. Core cache is scoped to this atlas only. */
const VERSION = 'gb-atlante-425b712e0409';
const CORE = ["./", "LICENSES.md", "METHODOLOGY.md", "README-MAP_10.md", "README.md", "SOURCES.md", "assets/stockdale-1812.jpg", "css/atlas.css", "data/MAP_01/atlas.json", "data/MAP_02/atlas.json", "data/MAP_03/atlas.json", "data/MAP_04/atlas.json", "data/MAP_05/atlas.json", "data/MAP_06/atlas.json", "data/MAP_07/atlas.json", "data/MAP_08/atlas.json", "data/MAP_09/atlas.json", "data/MAP_10/atlas.json", "data/MAP_10/entities.json", "data/MAP_10/issues.json", "data/MAP_10/persons.json", "data/MAP_10/relations.json", "data/MAP_11/atlas.json", "data/MAP_12/atlas.json", "data/MAP_13/atlas.json", "data/MAP_14/atlas.json", "data/MAP_15/atlas.json", "data/common/campaign-routes.geojson", "data/common/campaigns.json", "data/common/events.json", "data/common/geometries.geojson", "data/common/issues.json", "data/common/land.geojson", "data/common/polities.json", "data/common/snapshots.json", "data/common/sources.json", "icons/icon-192.png", "icons/icon-512.png", "icons/icon.svg", "icons/maskable-512.png", "index.html", "js/app.js", "js/model.js", "manifest.webmanifest", "vendor/maplibre-gl-shared.mjs", "vendor/maplibre-gl-worker.mjs", "vendor/maplibre-gl.css", "vendor/maplibre-gl.mjs"];
const PREFIX = 'gb-atlante-';
self.addEventListener('install', event => {
 event.waitUntil(caches.open(VERSION).then(cache => cache.addAll(CORE)));
});
self.addEventListener('activate', event => {
 event.waitUntil((async () => {
  for (const key of await caches.keys()) if (key.startsWith(PREFIX) && key !== VERSION) await caches.delete(key);
  await self.clients.claim();
 })());
});
self.addEventListener('message', event => {
 if (event.data?.type === 'ACTIVATE_UPDATE') self.skipWaiting();
});
self.addEventListener('fetch', event => {
 const url = new URL(event.request.url);
 if (event.request.method !== 'GET' || url.origin !== self.location.origin || !url.href.startsWith(self.registration.scope)) return;
 event.respondWith((async () => {
  const cache = await caches.open(VERSION);
  const cached = await cache.match(event.request, {ignoreSearch: true});
  if (cached) return cached;
  try { return await fetch(event.request); }
  catch (error) {
   if (event.request.mode === 'navigate') return await cache.match('./');
   return new Response('Risorsa non inclusa nella copia offline.', {status: 503, headers: {'Content-Type':'text/plain; charset=utf-8'}});
  }
 })());
});
